### ISSUE TITLE
Create basic express server as starting point for backend

### ISSUE THREAD

**Issue by BrandonManuel** [BrodyJack/MacroTracker#1]
![bitmoji](https://render.bitstrips.com/v2/cpanel/4d428482-1dad-4da8-ad6a-94f32f611f5d-1c7f8e0c-74a5-44f5-904e-b1d4a2944ceb-v1.png?transparent=1&palette=1&width=246)

**Comment by BrandonManuel** [comment]
Starting this on branch 1-express-backend

**Comment by BrandonManuel** [comment]
Basic express app created and base route /api version response put in place.

**Comment by BrandonManuel** [comment]
PR here https://github.com/BrodyJack/MacroTracker/pull/2

**Comment by BrodyJack** [comment]
Accepted and merged, closing issue
