### ISSUE TITLE
Create basic POST route for handling insertion of new items

### ISSUE THREAD

**Issue by BrandonManuel** [BrodyJack/MacroTracker#4]
For the time being, just save it in-memory. The posted information should be retrievable so long as the backend is running, but we don't need to submit to any actual database yet.

**Comment by BrandonManuel** [comment]
Branch will be 4-post-route

**Comment by BrandonManuel** [comment]
PR https://github.com/BrodyJack/MacroTracker/pull/5

**Comment by BrodyJack** [comment]
Accepted
