### ISSUE TITLE
Basic GET route to retrieve POST'ed items

### ISSUE THREAD

**Issue by BrandonManuel** [BrodyJack/MacroTracker#8]
For now, will just make it retrieve the in-memory food items array that has been created and added to through the POST route.

In the future, this will need authentication so you only GET items for a certain user.

Will add query params pageNumber and recordsPerPage so that we can support pagination.

**Comment by BrandonManuel** [comment]
Branch 8-get-request

**Comment by BrandonManuel** [comment]
PR https://github.com/BrodyJack/MacroTracker/pull/9

**Comment by BrodyJack** [comment]
Accepted
